

# backend/graph/agents/coder.py
# Only the _save_file function and the return block change
# Everything else stays the same
# backend/graph/agents/coder.py
import os
import ast
import uuid
import structlog
from langchain_core.messages import AIMessage
from tools.code_executor import execute_python
from tools.executors.c_executor import execute_c
from tools.executors.cpp_executor import execute_cpp
from tools.executors.js_executor import execute_javascript
from tools.executors.java_executor import execute_java
from tools.executors.go_executor import execute_go
from graph.state import AgentState
from typing import Tuple
from graph.llm import get_llm
try:
    from storage.supabase_storage import upload_generated_file
    SUPABASE_ENABLED = True
except Exception as e:
    print("SUPABASE IMPORT ERROR:", e)
    SUPABASE_ENABLED = False

log = structlog.get_logger()

# GENERATED_CODE_DIR = os.path.join(
#     os.path.dirname(__file__), "..", "..", "generated_code"

# )
GENERATED_CODE_DIR = r"C:\agentops_generated"
os.makedirs(GENERATED_CODE_DIR, exist_ok=True)


# def _clean_code(raw: str) -> str:
#     return raw.strip().replace("```python","").replace("```py","").replace("```","").strip()
def _clean_code(raw: str) -> str:

    raw = raw.strip()

    if "```" in raw:

        parts = raw.split("```")

        if len(parts) >= 2:

            code = parts[1]

            lines = code.splitlines()

            if lines and lines[0].lower() in [
                "python",
                "py",
                "javascript",
                "js",
                "java",
                "c",
                "cpp",
                "go",
                "typescript",
                "ts",
            ]:
                lines = lines[1:]

            return "\n".join(lines).strip()

    return raw

def _validate_syntax(code: str) -> tuple[bool, str]:
    try:
        ast.parse(code)
        return True, ""
    except SyntaxError as e:
        return False,  f"SyntaxError at line {e.lineno}, column {e.offset}: {e.msg}"


def _save_file(code: str, language: str, task_description: str) -> tuple[str, str]:
    """Save locally temporarily. Returns (filename, filepath)."""
    safe_name = "".join(
        c if c.isalnum() or c in " _-" else ""
        for c in task_description[:40]
    ).strip().replace(" ", "_")
    EXTENSIONS = {
    "python": ".py",
    "javascript": ".js",
    "jsx": ".jsx",
    "tsx": ".tsx",
    "typescript": ".ts",
    "java": ".java",
    "go": ".go",
    "rust": ".rs",
    "c": ".c",
    "cpp": ".cpp",
    "csharp": ".cs",
    "php": ".php",
    "ruby": ".rb",
    "bash": ".sh",
    "sql": ".sql",
}

    filename = (
        safe_name
        + "_"
        + uuid.uuid4().hex[:6]
        + EXTENSIONS.get(language, ".txt")
    )
    filepath = os.path.join(GENERATED_CODE_DIR, filename)
    COMMENT_PREFIX = {
    "python": "#",
    "bash": "#",

    "c": "//",
    "cpp": "//",
    "javascript": "//",
    "typescript": "//",
    "java": "//",
    "go": "//",
    "rust": "//",
}

    prefix = COMMENT_PREFIX.get(language, "#")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"{prefix} Task: {task_description}\n")
        f.write(f"{prefix} Generated by AgentOps Coder Agent\n\n")
        f.write(code)
    
    return filename, filepath
def detect_language(code: str) -> str:

    c = code.strip()
    lower = c.lower()

    # C++
    if "#include" in c and (
        "std::" in c
        or "iostream" in c
    ):
        return "cpp"

    # C
    if "#include" in c:
        return "c"

    # Rust
    if "fn main()" in c:
        return "rust"

    # Go
    if "package main" in c:
        return "go"

    # Java
    if "public class" in c:
        return "java"

    # C#
    if (
        "using system" in lower
        and "namespace" in c
    ):
        return "csharp"

    # PHP
    if "<?php" in lower:
        return "php"

    # Ruby
    if "puts " in c:
        return "ruby"

    # Bash
    if (
        c.startswith("#!/bin/bash")
        or c.startswith("#!/usr/bin/env bash")
    ):
        return "bash"

    # TSX
    if (
        "export default" in c
        and ("interface " in c or ": string" in c)
    ):
        return "tsx"

    # TypeScript
    if (
        "interface " in c
        or ": string" in c
    ):
        return "typescript"

    # React JSX
    if (
        "import react" in lower
        or "usestate(" in lower
        or "useeffect(" in lower
        or (
            "return (" in c
            and "<div" in c
        )
    ):
        return "jsx"

    # JavaScript
    if "console.log(" in c:
        return "javascript"

    # SQL
    if (
        "select " in lower
        or "create table" in lower
        or "insert into" in lower
    ):
        return "sql"

    return "python"

async def _generate_code(
    task: str,
    context: str,
    goal: str,
    user_id: str,
    attempt: int = 1,
    previous_error: str = "",
    previous_code: str = "",
) -> Tuple[str, int]:

    retry_note = f"""
IMPORTANT:

Previous code was invalid.

Compiler error:
{previous_error}

Broken code:
{previous_code[:3000]}
Fix the error and regenerate the COMPLETE file.

Return ONLY valid code.
Do NOT explain.
Do NOT summarize.
Do NOT use markdown fences.
""" if attempt > 1 else ""
    system_prompt =  f"""
You are an expert software engineer.

GOAL: {goal}

RULES:
1. Every line inside a function MUST be indented 4 spaces
2. NEVER place return outside functions.
3. If the task mentions FastAPI, LangGraph, OpenAI, React, SQL, Pandas, JavaScript, or Java, use the real framework/library.
4. NEVER use input() — hardcode sample values
5. NO markdown fences
6. For executable programs, include a visible demonstration of functionality appropriate to the language.
7. Generate complete working code.
8. When PREVIOUS CONTEXT contains research findings, incorporate them into the implementation.
9. Ensure valid syntax.
10.Prefer real implementations over demonstrations and placeholders.
11.If external packages are required, import them normally. Do not avoid libraries simply because they may not be installed.
12. PREVIOUS CONTEXT is the highest-priority source of technical truth.
13. If PREVIOUS CONTEXT specifies technologies, APIs, libraries, or architecture choices, use them exactly.
14. Do not substitute older, deprecated, or alternative frameworks.
15. If the task says "latest", prefer current official SDK syntax and patterns.
16. If PREVIOUS CONTEXT contains code examples, API usage patterns, class names, function names, or import statements, use them as implementation guidance.
17. Never invent APIs, classes, methods, endpoints, SDK calls, or package structures that are not present in PREVIOUS CONTEXT or the official library being used.
18. For comparison workflows, implement only the assigned approach. Do not combine multiple approaches into a single solution.
19. Before finishing, verify that:
    - syntax is valid for the target language
    - imports are valid for the target language
    - functions/classes are closed correctly
    - code follows conventions of the target language
CRITICAL:
Generate code in the exact language/framework requested.
Examples:
- React -> JSX/TSX
- Next.js -> TSX
- Java -> Java
- Go -> Go
- Rust -> Rust
- SQL -> SQL
- Bash -> Bash
- Python -> Python

All syntax, imports, validation rules,
and code style must match the target language.

Never apply Python rules to non-Python tasks.

PREVIOUS CONTEXT is authoritative.

If PREVIOUS CONTEXT specifies:
- technologies
- frameworks
- APIs
- SDKs
- imports
- classes
- functions
- architecture decisions

you MUST follow them exactly.

Do not:
- substitute alternatives
- downgrade to older APIs
- replace requested technologies
- generate placeholder implementations
- invent SDK methods

Examples:
- OpenAI Responses API -> use Responses API
- StateGraph -> use langgraph.graph.StateGraph
- FastAPI -> use FastAPI
- React -> use React
- OpenAI SDK example -> follow the example pattern

If PREVIOUS CONTEXT conflicts with your prior knowledge,
follow PREVIOUS CONTEXT.

Before generating code:

Extract all technologies, APIs, classes, SDK methods,
and imports mentioned in PREVIOUS CONTEXT.

Your implementation MUST use those exact technologies.

If PREVIOUS CONTEXT mentions:
- OpenAI Responses API
then use the official Responses API SDK pattern.
Do NOT use ChatCompletion, Completion, Assistants API, or legacy OpenAI APIs.
If PREVIOUS CONTEXT mentions:
- StateGraph
then import:
from langgraph.graph import StateGraph

Do NOT invent alternative LangGraph imports.

Code that ignores PREVIOUS CONTEXT is incorrect.
Before returning code, verify that:

1. Every framework, API, SDK, import, and class requested by the task or PREVIOUS CONTEXT is present in the implementation.
2. No deprecated or alternative APIs replaced the requested technology.
3. The generated code directly reflects the research findings.

If these checks fail, regenerate the code before responding.
PREVIOUS CONTEXT:
{context if context else "None"}
{retry_note}
"""
    llm = await get_llm(user_id)
    response = await llm.ainvoke([
        {"role": "system", "content": system_prompt},
        {"role":"user","content":f"""
Task:
{task}

Generate complete runnable code.

Requirements:
-Use the actual framework, library, or API requested.

IMPORTANT:
- Follow PREVIOUS CONTEXT exactly.
- Use technologies mentioned in PREVIOUS CONTEXT.
- Do not substitute frameworks.
- Prefer current official SDK syntax.
- Use research findings from context when available.
- Prefer production-quality implementations.
- Do not invent fake APIs.
- Do not hardcode fake IDs or placeholder responses.
- Use real imports and real library patterns.
- If information is missing, make reasonable assumptions and document them in code comments.
"""}
    ])
    tokens_used = (
    getattr(response, "usage_metadata", {})
    .get("total_tokens", 0)
)

    return (
        _clean_code(response.content),
        tokens_used,
    )



async def coder_node(state: AgentState) -> dict:
    results = state.get("results", {})
    plan    = state.get("plan", [])
    goal    = state.get("goal", "")
    user_id = state.get("user_id", "anonymous")  # ← get user_id from state

    pending = [
        t for t in plan
        if (
            t.get("assigned_to") == "coder"
            and t.get("id") not in results
            and all(d in results for d in t.get("depends_on", []))
        )
    ]

    if not pending:
        failed = [tid for tid, r in results.items()
                  if isinstance(r, str) and  ("Syntax Error" in r or "Execution Environment Error" in r)]
        if failed:
            return {"approved": False, "next": "END",
                    "messages": [AIMessage(content="Coder: no runnable tasks remain.")]}
        return {"messages": [AIMessage(content="Coder: nothing to do")]}

    task = pending[0]
    all_context = "\n\n".join(
        f"""
    RESEARCH / PREVIOUS RESULT ({tid}):

    {str(res)[:2000]}
    """
        for tid, res in results.items()
    )
    print("\n===== CODER CONTEXT =====")
    print(all_context[:3000])
    print("=========================\n")
# Generate + validate
    code, tokens_used = await _generate_code(
        task.get("task", ""),
        all_context,
        goal,
        user_id,
        attempt=1,
    )

    state["tokens_used"] = (
        (state.get("tokens_used") or 0)
        + tokens_used
    )
    code = _clean_code(code)
    language = detect_language(code)
    print("\n===== LANGUAGE DETECTED =====")
    print(language)
    print("============================\n")
    is_valid = True
    syntax_err = ""

    if language == "python":
         is_valid, syntax_err = _validate_syntax(code)

    # if language == "python":
    #     is_valid, syntax_err = _validate_syntax(code)
    # else:
    #     is_valid,
    #     syntax_err = True,""
       

    # Retry once if syntax invalid
    if not is_valid:

        bad_code = code

        code, retry_tokens = await _generate_code(
            task.get("task", ""),
            all_context,
            goal,
            user_id,
            attempt=2,
            previous_error=syntax_err,
            previous_code=bad_code,
        )

        state["tokens_used"] = (
            (state.get("tokens_used") or 0)
            + retry_tokens
        )
        if language == "python":
          is_valid, syntax_err = _validate_syntax(code)
        else:
            is_valid = True
            syntax_err = ""

        if not is_valid:

       
            print("\n===== INVALID GENERATED CODE =====")
            print(code)
            print("=================================\n")

            filename, filepath = _save_file(
                code,
                language,
                task.get("task", "generated")
            )

            exec_result = (
                "Syntax Error\n\n"
                f"{syntax_err}"
            )

            print(
                "CODER TOTAL TOKENS =",
                state.get("tokens_used", 0)
            )

            return {
                "results": {
                    **results,
                    task.get("id"): exec_result
                },
                "messages": [AIMessage(
                    content=(
                        f"TASK:\n{task.get('task')}\n\n"
                        f"SAVED AS: {filename}\n\n"
                        f"GENERATED CODE:\n\n{code}\n\n"
                        f"EXECUTION RESULT:\n\n{exec_result}"
                    )
                )]
            }
        print("\n===== FILE SAVE =====")
        print("LANGUAGE =", language)
        print("=====================\n")
    # Save locally first (needed for execution)
    filename, filepath = _save_file(code, language,task.get("task", "generated"))

    # Execute code
    # Execute code
    try:

        if language == "python":
                exec_result = await execute_python(code)

        elif language == "c":
                exec_result = await execute_c(filepath)

        elif language in ["cpp", "c++"]:
                exec_result = await execute_cpp(filepath)

        elif language in ["javascript", "js"]:
                exec_result = await execute_javascript(filepath)

        elif language == "java":
                exec_result = await execute_java(filepath)

        elif language == "go":
                exec_result = await execute_go(filepath)

        else:
                exec_result = (
                    f"{language.upper()} code generated successfully. "
                    f"Execution not supported."
                )
    # try:
    #     if language == "python":
    #         exec_result = await execute_python(code)

    #     else:

    #         exec_result = (
    #             f"{language.upper()} code generated successfully. "
    #             f"Execution not supported."
    #         )
    except Exception as e:
        exec_result = ("Execution Environment Error\n\n"f"{str(e)}")

    signed_url = ""
    storage_path = ""

    if SUPABASE_ENABLED:

        upload_result = await upload_generated_file(
            filepath,
            user_id
        )

        if upload_result:

            signed_url = upload_result.get(
                "signed_url",
                ""
            )

            storage_path = upload_result.get(
                "storage_path",
                ""
            )
            if (
            os.path.exists(filepath)
            and filepath.startswith(
                r"C:\agentops_generated"
            )
        ):
             os.remove(filepath)

    log.info(
        "coder_done",
        task_id=task.get("id"),
        filename=filename,
        user=user_id,
        storage_path=storage_path,
    )

    url_line = (
        f"\nSIGNED URL: {signed_url}"
        if signed_url else ""
    )

    return {
        "tokens_used": state.get("tokens_used", 0),
        "results": {
            **results,
            task.get("id"): exec_result
        },

        "messages": [
            AIMessage(
                content=(

                    f"TASK:\n{task.get('task')}\n\n"

                    f"SAVED AS: {filename}"
                    f"{url_line}\n\n"

                    f"GENERATED CODE:\n\n"
                    f"{code}\n\n"

                    f"EXECUTION RESULT:\n\n"
                    f"{str(exec_result)[:500]}"
                )
            )
        ]
    }